import React, { useEffect, useState } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism'
import Card from '../components/Card'
import Button from '../components/Button'
import Badge from '../components/Badge'
import { 
  FileText, 
  ChevronLeft, 
  Download, 
  Copy, 
  Check,
  FileJson,
  Loader2,
  AlertCircle
} from 'lucide-react'
import { motion } from 'framer-motion'

const FileViewer: React.FC = () => {
  const { '*': filePath } = useParams()
  const navigate = useNavigate()
  const [content, setContent] = useState<string>('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [fileType, setFileType] = useState<'markdown' | 'json' | 'text'>('text')

  useEffect(() => {
    if (filePath) {
      loadFile(filePath)
    }
  }, [filePath])

  const loadFile = async (path: string) => {
    setLoading(true)
    setError(null)

    try {
      // Determine file type
      if (path.endsWith('.md')) {
        setFileType('markdown')
      } else if (path.endsWith('.json')) {
        setFileType('json')
      } else {
        setFileType('text')
      }

      // Simulated file loading - replace with actual API call
      const response = await fetch(`/api/files/${path}`)
      if (!response.ok) {
        throw new Error('File not found')
      }
      const text = await response.text()
      setContent(text)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load file')
      // Mock data for demonstration
      if (path?.includes('deepresearch_report.md')) {
        setContent(`# Deep Research Report

## Executive Summary

This report presents the findings from our symbolic regression analysis on the provided dataset. The analysis aimed to discover mathematical relationships between input variables and the target output.

### Key Findings

1. **Best Expression Found**: \`y = 2.5x₁² + 3.7x₂ - 1.2x₁x₂ + 0.8\`
2. **Model Accuracy**: R² = 0.987, MSE = 0.0124
3. **Computational Time**: 45 seconds across 1000 iterations

## Methodology

We employed the Py (Python Symbolic Regression) library with the following configuration:

- **Populations**: 50
- **Iterations**: 1000
- **Binary Operators**: ['+', '-', '*', '/']
- **Unary Operators**: ['square', 'cube', 'exp', 'log', 'sqrt']

### Data Analysis

The input dataset consisted of:
- 500 samples
- 3 input features (x₁, x₂, x₃)
- 1 target variable (y)

\`\`\`python
# Data statistics
mean_x1 = 2.34
mean_x2 = 5.67
mean_y = 12.45

std_x1 = 0.89
std_x2 = 1.23
std_y = 3.45
\`\`\`

## Results

### Top Expressions by Complexity

| Complexity | MSE    | Expression                           |
|------------|--------|--------------------------------------|
| 5          | 0.0124 | 2.5x₁² + 3.7x₂ - 1.2x₁x₂ + 0.8     |
| 7          | 0.0098 | exp(0.5x₁) + 2.3x₂² - 0.9x₃        |
| 9          | 0.0087 | sqrt(x₁²+x₂²) * 1.8 + log(x₃+1)    |

### Convergence Analysis

The algorithm showed rapid convergence in the first 200 iterations, with diminishing improvements thereafter.

## Conclusions

The discovered expressions provide interpretable models for the underlying data relationships. The quadratic term in x₁ suggests a non-linear relationship with the target variable.

## Recommendations

1. Consider expanding the operator set to include trigonometric functions
2. Increase population size for more complex datasets
3. Apply domain-specific constraints where applicable

---

*Report generated by Agent- on ${new Date().toISOString()}*`)
      } else if (path?.includes('iteration_history.json')) {
        setContent(JSON.stringify({
          iterations: [
            {
              id: 1,
              timestamp: "2024-01-15T10:30:00Z",
              best_expression: "2.5x₁² + 3.7x₂",
              mse: 0.0156,
              complexity: 4
            },
            {
              id: 2,
              timestamp: "2024-01-15T10:35:00Z",
              best_expression: "2.5x₁² + 3.7x₂ - 1.2x₁x₂",
              mse: 0.0134,
              complexity: 5
            },
            {
              id: 3,
              timestamp: "2024-01-15T10:40:00Z",
              best_expression: "2.5x₁² + 3.7x₂ - 1.2x₁x₂ + 0.8",
              mse: 0.0124,
              complexity: 5
            }
          ],
          total_iterations: 3,
          convergence_achieved: true
        }, null, 2))
      }
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filePath?.split('/').pop() || 'file.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const renderContent = () => {
    if (loading) {
      return (
        <div className="flex items-center justify-center h-64">
          <Loader2 className="w-8 h-8 text-apple-gray-400 animate-spin" />
        </div>
      )
    }

    if (error && !content) {
      return (
        <div className="flex flex-col items-center justify-center h-64 text-apple-gray-500">
          <AlertCircle className="w-12 h-12 mb-3" />
          <p className="text-lg font-medium">无法加载文件</p>
          <p className="text-sm mt-1">{error}</p>
        </div>
      )
    }

    switch (fileType) {
      case 'markdown':
        return (
          <div className="markdown-content">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                code({ node, inline, className, children, ...props }: any) {
                  const match = /language-(\w+)/.exec(className || '')
                  return !inline && match ? (
                    <SyntaxHighlighter
                      style={vscDarkPlus}
                      language={match[1]}
                      PreTag="div"
                      {...props}
                    >
                      {String(children).replace(/\n$/, '')}
                    </SyntaxHighlighter>
                  ) : (
                    <code className={className} {...props}>
                      {children}
                    </code>
                  )
                },
              }}
            >
              {content}
            </ReactMarkdown>
          </div>
        )

      case 'json':
        try {
          const jsonData = JSON.parse(content)
          return (
            <SyntaxHighlighter
              language="json"
              style={vscDarkPlus}
              customStyle={{
                margin: 0,
                borderRadius: '0.5rem',
              }}
            >
              {JSON.stringify(jsonData, null, 2)}
            </SyntaxHighlighter>
          )
        } catch {
          return <pre className="code-block">{content}</pre>
        }

      default:
        return <pre className="code-block">{content}</pre>
    }
  }

  const getFileIcon = () => {
    switch (fileType) {
      case 'markdown':
        return <FileText className="w-5 h-5" />
      case 'json':
        return <FileJson className="w-5 h-5" />
      default:
        return <FileText className="w-5 h-5" />
    }
  }

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="glass border-b border-apple-gray-200/50 px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="sm"
              icon={<ChevronLeft className="w-4 h-4" />}
              onClick={() => navigate(-1)}
            >
              返回
            </Button>
            <div className="flex items-center gap-2">
              {getFileIcon()}
              <h2 className="text-lg font-medium text-apple-gray-900">
                {filePath?.split('/').pop() || 'File'}
              </h2>
              <Badge variant="info" className="ml-2">
                {fileType.toUpperCase()}
              </Badge>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="sm"
              icon={copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              onClick={handleCopy}
            >
              {copied ? '已复制' : '复制'}
            </Button>
            <Button
              variant="secondary"
              size="sm"
              icon={<Download className="w-4 h-4" />}
              onClick={handleDownload}
            >
              下载
            </Button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.3 }}
        >
          <Card className="min-h-[calc(100vh-200px)]">
            {renderContent()}
          </Card>
        </motion.div>
      </div>
    </div>
  )
}

export default FileViewer